apiVersion: apm.cloudruntime.vmware.com/v1alpha1
kind: Alo
metadata:
  name: bookinfo-alo
spec:
  gns: crdemo
  cloudruntimeIdentifier: cr-demo-1
  tlos:
  - reviews-tlo
  clo: bookinfo-clo
  elos:
  - ratings-vm-elo
  remediations:
    awsAsg:
      elo: ratings-vm-elo
      metricName: cloudRuntime-demo-ASG-custom-metric1
      awsAccessKeyId: ASIARRL6APZJL5LPKSUR
      awsAccessSecret: oWaBT7pGJAPu3NVKkLs3CP/WEJWqEV41ZIYQ+VJx
      awsSessionToken: IQoJb3JpZ2luX2VjEPP//////////wEaCXVzLWVhc3QtMSJIMEYCIQDTVKSY+2eTwIA0RoWg6sb6bMSVZKaWuIPTpOLLxsTMHQIhAPgTb2wEFLDUY+WmSZq1aKqOKR94RlYkj7p7XhloUQI2KqkCCIz//////////wEQABoMMTA2MDI3ODQzMTU0IgxywGFAx4+n6CnxYvwq/QFGn7V6VbqGU0s1pVlfZBpRBrioHBxwU0XpQDMzo4ezznYG7krbh9ezzeW71bWNkAjIghkYJ3IkxbUw6Q/bV2dNiqM8OS6peiSoyUn+sFkYd6RyXqKQe/rp19lmv8WRffSJosclXYxPtKoLSnDHhWbMUVDT9FQYSVmyqVJdG5/XwGx4D2/vAnxThSPGmSwBAmHaj5T62hyuU4k9Cc2Kx625MU4MwHep1oJ3b9fOscb+sUEJjnZGmgi8lXFdW/fv2a9kHfIPTf3BIgOku9LfeZQuVd2DQpRA/bk/od4aBvgCBlbj8qPfcJ8B5BQM+JshqtbpSg+1cG7T9lmqQloxMLTi5IsGOpwBZ6hrCYrRwrWmuskCwxmlRcetWDxQJLmhB8T6ppMG6q+GlSRltsy7PDAi3y5xiFgeA6d6EuhAIG1CBhqjlH16qrxyhE+LTj2vwRN79T13aKxFPuPyp9pKS/NjxPQKYUMG6dhNZCZFVReIDJUjbAcuSJBxmn443mEPQXabmWtNuF+Xf1ggc4Pm7ZMfmTiDJKfeuO3roUcU4eS402bn
---
apiVersion: apm.cloudruntime.vmware.com/v1alpha1
kind: Tlo
metadata:
  name: reviews-tlo
spec:
  aloName: bookinfo-alo
  tlis:
  - name: P50LATENCY
    value: 1500
  - name: P90LATENCY
    value: 1750
  transactionType: reviews_vm
  operationName: reviews_vm
  serviceName: reviews
---
apiVersion: apm.cloudruntime.vmware.com/v1alpha1
kind: ExternalLo
metadata:
  name: ratings-vm-elo
spec:
  type: VM
  elis:
  - name: P50LATENCY
    value: 200
  - name: P90LATENCY
    value: 250
  spanName: ratings_vm
---
apiVersion: apm.cloudruntime.vmware.com/v1alpha1
kind: Clo
metadata:
  name: bookinfo-clo
spec:
  gns: crdemo
  aloName: bookinfo-alo
  clis:
  - name: CPUUTILIZATION
    value: 95
  - name: MEMORYUTILIZATION
    value: 95