apiVersion: apm.cloudruntime.vmware.com/v1alpha1
kind: Alo
metadata:
  name: bookinfo-alo
spec:
  gns: crdemo
  cloudruntimeIdentifier: cr-demo-1
  tlos:
  - reviews-tlo
  clo: bookinfo-clo
  elos:
  - ratings-tas-elo
  remediations:
    tas:
      - elo: ratings-tas-elo
        maxInstances: 4
        minInstances: 1
        serviceName: bookinfo-ratings
        metricName: cr_ratings_tas_metric
---
apiVersion: apm.cloudruntime.vmware.com/v1alpha1
kind: Tlo
metadata:
  name: reviews-tlo
spec:
  aloName: bookinfo-alo
  tlis:
  - name: P50LATENCY
    value: 1500
  - name: P90LATENCY
    value: 1750
  transactionType: reviews_tas
  operationName: reviews_tas
  serviceName: reviews
---
apiVersion: apm.cloudruntime.vmware.com/v1alpha1
kind: ExternalLo
metadata:
  name: ratings-tas-elo
spec:
  type: TAS
  elis:
  - name: P50LATENCY
    value: 200
  - name: P90LATENCY
    value: 250
  spanName: ratings_tas
---
apiVersion: apm.cloudruntime.vmware.com/v1alpha1
kind: Clo
metadata:
  name: bookinfo-clo
spec:
  gns: crdemo
  aloName: bookinfo-alo
  clis:
  - name: CPUUTILIZATION
    value: 95
  - name: MEMORYUTILIZATION
    value: 95